/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : KiLLraVeN/MYSTiC
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_KC_Users                            0
#define GD_KC_RC_ALIAS                         1
#define GD_KC_RC_INFO                          2
#define GD_KC_RC_COMMENTFILE                   3
#define GD_KC_RC_NAME                          4
#define GD_KC_RC_ADD                           5
#define GD_KC_RC_DEL                           6
#define GD_KC_SAVE_QUIT                        7
#define GD_KC_QUIT                             8
#define GD_KC_STATISTICS                       9
#define GD_KC_SELECT_COMMENTS                  10
#define GD_KC_DOWN                             11
#define GD_KC_UP                               12
#define GD_KC_SAVEQUIT                         13
#define GD_KC_MIN_ACS                          14
#define GD_KC_CLEAR_ACCOUNT                    15

#define GDX_KC_Users                           0
#define GDX_KC_RC_ALIAS                        1
#define GDX_KC_RC_INFO                         2
#define GDX_KC_RC_COMMENTFILE                  3
#define GDX_KC_RC_NAME                         4
#define GDX_KC_RC_ADD                          5
#define GDX_KC_RC_DEL                          6
#define GDX_KC_SAVE_QUIT                       7
#define GDX_KC_QUIT                            8
#define GDX_KC_STATISTICS                      9
#define GDX_KC_SELECT_COMMENTS                 10
#define GDX_KC_DOWN                            11
#define GDX_KC_UP                              12
#define GDX_KC_SAVEQUIT                        13
#define GDX_KC_MIN_ACS                         14
#define GDX_KC_CLEAR_ACCOUNT                   15

#define GD_KC_SELECT_USER                      0
#define GD_KC_CANCEL                           1

#define GDX_KC_SELECT_USER                     0
#define GDX_KC_CANCEL                          1

#define KiLLER_COMMENT_CNT 16
#define USER_SELECTION_CNT 2

extern struct Library		 *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *KiLLER_COMMENTWnd;
extern struct Window        *USER_SELECTIONWnd;
extern struct Gadget        *KiLLER_COMMENTGList;
extern struct Gadget        *USER_SELECTIONGList;
extern struct Gadget        *KiLLER_COMMENTGadgets[16];
extern struct Gadget        *USER_SELECTIONGadgets[2];
extern UWORD                 KiLLER_COMMENTLeft;
extern UWORD                 KiLLER_COMMENTTop;
extern UWORD                 KiLLER_COMMENTWidth;
extern UWORD                 KiLLER_COMMENTHeight;
extern UWORD                 USER_SELECTIONLeft;
extern UWORD                 USER_SELECTIONTop;
extern UWORD                 USER_SELECTIONWidth;
extern UWORD                 USER_SELECTIONHeight;
extern UBYTE                *KiLLER_COMMENTWdt;
extern UBYTE                *USER_SELECTIONWdt;
extern struct MinList        KC_Users0List;
extern struct MinList        KC_SELECT_USER1List;
extern struct TextAttr       topaz8;
extern struct IntuiText      KiLLER_COMMENTIText[];
extern UWORD                 KiLLER_COMMENTGTypes[];
extern UWORD                 USER_SELECTIONGTypes[];
extern struct NewGadget      KiLLER_COMMENTNGad[];
extern struct NewGadget      USER_SELECTIONNGad[];
extern ULONG                 KiLLER_COMMENTGTags[];
extern ULONG                 USER_SELECTIONGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void KiLLER_COMMENTRender( void );
extern int OpenKiLLER_COMMENTWindow( void );
extern void CloseKiLLER_COMMENTWindow( void );
extern int OpenUSER_SELECTIONWindow( void );
extern void CloseUSER_SELECTIONWindow( void );
