/**
 * ACS (Access Control System) Permission Codes
 * 1:1 port from express.e lines 31528-31537
 *
 * These permission codes control user access to various BBS features.
 * Each permission is checked via checkSecurity(ACS_*) function.
 */

// Permission indices (0-based array positions)
export enum ACSPermission {
  // Line 31529 - Basic user operations (0-8)
  ACCOUNT_EDITING = 0,
  READ_BULLETINS = 1,
  COMMENT_TO_SYSOP = 2,
  DOWNLOAD = 3,
  UPLOAD = 4,
  ENTER_MESSAGE = 5,
  FILE_LISTINGS = 6,
  JOIN_CONFERENCE = 7,
  NEW_FILES_SINCE = 8,

  // Line 31530 - User actions and editing (9-20)
  PAGE_SYSOP = 9,
  READ_MESSAGE = 10,
  REMOTE_SHELL = 11,
  DISPLAY_USER_STATS = 12,
  VIEW_A_FILE = 13,
  EDIT_USER_INFO = 14,
  EDIT_INTERNET_NAME = 15,
  EDIT_USER_LOCATION = 16,
  EDIT_PHONE_NUMBER = 17,
  EDIT_PASSWORD = 18,
  ZIPPY_TEXT_SEARCH = 19,
  OVERRIDE_CHAT = 20,

  // Line 31531 - Sysop features and system settings (21-32)
  SYSOP_DOWNLOAD = 21,
  SYSOP_VIEW = 22,
  SYSOP_READ = 23,
  KEEP_UPLOAD_CREDIT = 24,
  OVERRIDE_TIMES = 25,
  CLEAR_SCREEN_MSG = 26,
  FREE_RESUMING = 27,
  ONE_TIME_BULLETINS = 28,
  DO_CALLERSLOG = 29,
  SENTBY_FILES = 30,
  DO_UD_LOG = 31,
  SCREEN_TO_FRONT = 32,

  // Line 31532 - Message and conference features (33-44)
  DEFAULT_CHAT_ON = 33,
  EALL_MESSAGES = 34,
  DUPE_FILECHECK = 35,
  MESSAGE_EDIT = 36,
  LIST_NODES = 37,
  MSG_LEVEL = 38,
  MSG_EXPERATION = 39,
  DELETE_MESSAGE = 40,
  ATTACH_FILES = 41,
  CUSTOMCOMMANDS = 42,
  JOIN_SUB_CONFERENCE = 43,
  ZOOM_MAIL = 44,

  // Line 31533 - Advanced features (45-56)
  MCI_MESSAGE = 45,
  EDIT_DIRS = 46,
  EDIT_FILES = 47,
  BREAK_CHAT = 48,
  QUIET_NODE = 49,
  SYSOP_COMMANDS = 50,
  WHO_IS_ONLINE = 51,
  RELOGON = 52,
  ULSTATS = 53,
  XPR_RECEIVE = 54,
  XPR_SEND = 55,
  WILDCARDS = 56,

  // Line 31534 - Conference and file features (57-68)
  CONFERENCE_ACCOUNTING = 57,
  PRI_MSGFILES = 58,
  PUB_MSGFILES = 59,
  FULL_EDIT = 60,
  CONFFLAGS = 61,
  OLM = 62,
  HIDE_FILES = 63,
  SHOW_PAYMENTS = 64,
  CREDIT_ACCESS = 65,
  VOTE = 66,
  MODIFY_VOTE = 67,
  FILE_EXPANSION = 68,

  // Line 31535 - User profile editing (69-80)
  EDIT_REAL_NAME = 69,
  EDIT_USER_NAME = 70,
  CENSORED = 71,
  ACCOUNT_VIEW = 72,
  TRANSLATION = 73,
  UNKNOWN = 74,
  CREATE_CONFERENCE = 75,
  LOCAL_DOWNLOADS = 76,
  MAX_PAGES = 77,
  OVERRIDE_DEFAULTS = 78,
  HOLD_ACCESS = 79,
  EDIT_EMAIL = 80,

  // Line 31536-31537 - Advanced permissions (81-86)
  READ_PRIV_EALL = 81,
  READ_PRIV_ALL = 82,
  OVERRIDE_TIMELIMIT = 83,
  OVERRIDE_CHATLIMIT = 84,
  NO_TIMEOUT = 85,
  USER_ULSTATS = 86
}

// Human-readable permission names (same order as express.e)
export const ACS_PERMISSION_NAMES: string[] = [
  // Line 31529
  'ACS.ACCOUNT_EDITING', 'ACS.READ_BULLETINS', 'ACS.COMMENT_TO_SYSOP', 'ACS.DOWNLOAD', 'ACS.UPLOAD',
  'ACS.ENTER_MESSAGE', 'ACS.FILE_LISTINGS', 'ACS.JOIN_CONFERENCE', 'ACS.NEW_FILES_SINCE',

  // Line 31530
  'ACS.PAGE_SYSOP', 'ACS.READ_MESSAGE', 'ACS.REMOTE_SHELL', 'ACS.DISPLAY_USER_STATS', 'ACS.VIEW_A_FILE',
  'ACS.EDIT_USER_INFO', 'ACS.EDIT_INTERNET_NAME', 'ACS.EDIT_USER_LOCATION', 'ACS.EDIT_PHONE_NUMBER',
  'ACS.EDIT_PASSWORD', 'ACS.ZIPPY_TEXT_SEARCH', 'ACS.OVERRIDE_CHAT',

  // Line 31531
  'ACS.SYSOP_DOWNLOAD', 'ACS.SYSOP_VIEW', 'ACS.SYSOP_READ', 'ACS.KEEP_UPLOAD_CREDIT', 'ACS.OVERRIDE_TIMES',
  'ACS.CLEAR_SCREEN_MSG', 'ACS.FREE_RESUMING', 'ACS.ONE_TIME_BULLETINS', 'ACS.DO_CALLERSLOG',
  'ACS.SENTBY_FILES', 'ACS.DO_UD_LOG', 'ACS.SCREEN_TO_FRONT',

  // Line 31532
  'ACS.DEFAULT_CHAT_ON', 'ACS.EALL_MESSAGES', 'ACS.DUPE_FILECHECK', 'ACS.MESSAGE_EDIT', 'ACS.LIST_NODES',
  'ACS.MSG_LEVEL', 'ACS.MSG_EXPERATION', 'ACS.DELETE_MESSAGE', 'ACS.ATTACH_FILES', 'ACS.CUSTOMCOMMANDS',
  'ACS.JOIN_SUB_CONFERENCE', 'ACS.ZOOM_MAIL',

  // Line 31533
  'ACS.MCI_MESSAGE', 'ACS.EDIT_DIRS', 'ACS.EDIT_FILES', 'ACS.BREAK_CHAT', 'ACS.QUIET_NODE',
  'ACS.SYSOP_COMMANDS', 'ACS.WHO_IS_ONLINE', 'ACS.RELOGON', 'ACS.ULSTATS', 'ACS.XPR_RECEIVE',
  'ACS.XPR_SEND', 'ACS.WILDCARDS',

  // Line 31534
  'ACS.CONFERENCE_ACCOUNTING', 'ACS.PRI_MSGFILES', 'ACS.PUB_MSGFILES', 'ACS.FULL_EDIT', 'ACS.CONFFLAGS',
  'ACS.OLM', 'ACS.HIDE_FILES', 'ACS.SHOW_PAYMENTS', 'ACS.CREDIT_ACCESS', 'ACS.VOTE', 'ACS.MODIFY_VOTE',
  'ACS.FILE_EXPANSION',

  // Line 31535
  'ACS.EDIT_REAL_NAME', 'ACS.EDIT_USER_NAME', 'ACS.CENSORED', 'ACS.ACCOUNT_VIEW', 'ACS.TRANSLATION',
  'ACS.UNKNOWN', 'ACS.CREATE_CONFERENCE', 'ACS.LOCAL_DOWNLOADS', 'ACS.MAX_PAGES', 'ACS.OVERRIDE_DEFAULTS',
  'ACS.HOLD_ACCESS', 'ACS.EDIT_EMAIL',

  // Line 31536-31537
  'ACS.READ_PRIV_EALL', 'ACS.READ_PRIV_ALL', 'ACS.OVERRIDE_TIMELIMIT', 'ACS.OVERRIDE_CHATLIMIT',
  'ACS.NO_TIMEOUT', 'ACS.USER_ULSTATS'
];

// Total number of permissions (should be 87)
export const ACS_PERMISSION_COUNT = ACS_PERMISSION_NAMES.length;

/**
 * Get permission name by index
 */
export function getPermissionName(index: number): string {
  if (index >= 0 && index < ACS_PERMISSION_NAMES.length) {
    return ACS_PERMISSION_NAMES[index];
  }
  return 'ACS.UNKNOWN';
}

/**
 * Get permission index by name
 */
export function getPermissionIndex(name: string): number {
  return ACS_PERMISSION_NAMES.indexOf(name);
}
