;INI for Exorcist! v3.0 (do NOT remove this line!!)

; Don't use spaces before or after the = sign
; Use strings this way: "string"
; Use '\n' for newline
;     '\f' for formfeed (clear screen)
; All paths must have an ':' or '/' as last character

******************************************************************************
[Paths]
Acp="SYS:WBStartup/"                    ;/X v3.xx only
UserData="BBS:user.data"                ;/X v2.3x & S-Express only
AwardCmt="PROGDIR:Ex!_Award.cmt"
DeductCmt="PROGDIR:Ex!_Deduct.cmt"
ExpellCmt="PROGDIR:Ex!_Expell.cmt"
LogosCmt="PROGDIR:Ex!_Logos.cmt"
SizeCmt="PROGDIR:Ex!_Size.cmt"
Stats="BBS:Ex!_Stats"
Resurrect="BBS:Resurrect/"

******************************************************************************
[Levels]
;This section is for /X v2.3x & S-Express only
Award=255
Comment=255
Deduct=255
EditCmt=255
Expell=255
Free=255
MoveFiles=255
Resurrect=255

Anonymous=255
Wildcard=255

******************************************************************************
[Comments]
LineStart=">>>"
LineEnd="<<<Ex!"
SmallCmt="ASK"                          ;YES,NO or ASK
StripCmt="YES"                          ;YES,NO
MaxCmtLines=8

******************************************************************************
[Messages]
Uploader="ASK"                          ;YES,NO or ASK
Downloader="ASK"                        ;YES,NO or ASK
Sysop="YES"                             ;YES or NO
Public="NO"                             ;YES or NO

Anonymous=">>> anonymous <<<"
Subject=">>> Exorcist! message <<<"
Header="<<< Note of %s >>>\n\n"         ;%s = action
Action_Award="awarded credits"
Action_Comment="commented files"
Action_Create="created files"
Action_Deduct="deducted files"
Action_Edit="edited filecomments"
Action_Expell="expelled credits"
Action_Free="freed files"
Action_Move="moved files"
Action_Resurrect="resurrected files"
Action_Return="returned credits"

;%FN = FileName                             (12)
;%FS = FileSize                             ( 7)
;%FC = FileComment                          (??)
;%SC = SizeComment                          (10)
;%TI = Times awarded or deducted            ( 3)
;%TO = Total bytes (= FileSize * Times)     (10)
;%BT = Byte Type (= "u/l" or "d/l")         ( 3)
;%AC = Action (= "given" or "taken")        ( 5)
Files="%FN: %TI x %FS = %TO\n     sizecmt: %SC\n     comment: %FC\n"
;ONLY %FN,%FS,%FC,%SC are allowed
Files_NoTotal="%FN (%FS bytes)\n     sizecmt: %SC\n     comment: %FC\n"

;%PB = Previous bytes                         (10)
;%PF = Previous files                         ( 5)
;%CB = Current bytes                          (10)
;%CF = Current files                          ( 5)
;%TB = Total bytes                            (10)
;%TF = Total files                            ( 5)
;%TY = Type (= "uploaded" or "downloaded")    (10)
;%BT = Byte Type (= "u/l" or "d/l")           ( 3)
;%AC = Action (= "given" or "taken")          ( 5)
Result="\nPreviously %TY: %PB bytes\nTotal %AC credits:   %TB bytes\n---------------------------------------\nCurrently %TY:  %CB bytes\n\n<<< Delete this message when read >>>\n"
;no format codes are allowed
Result_NoTotal="\n<<< Delete this message when read >>>\n"
******************************************************************************
[Misc]
KeepLog="YES"                           ;YES or NO
KeepStats="YES"                         ;YES or NO
IndividualReturning="ASK"               ;YES,NO or ASK

******************************************************************************
[ActionStrings]
;for large comments (%d is times credits)
Award_L="%d TIMES CREDITS AWARDED!"
Deduct_L="%d TIMES CREDITS DEDUCTED!"
Expell_L="%d TIMES CREDITS EXPELLED!"
Free_L="FILE IS FREE-DOWNLOAD!"
Resurrect_L="FILE IS RESURRECTED!"

;for small comments (14 chars max)
Free_S="FREE DOWNLOAD"
Resurrect_S="RESURRECTED"
