services:
  - type: web
    name: amiexpress-backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    port: 3001
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

# Render.com specific configuration for WebSocket support
build:
  builder: nixpacks
  buildCommand: "npm ci --only=production"

# Environment variables for production
env:
  NODE_ENV: production
  PORT: 3001

# WebSocket configuration
network:
  protocol: tcp
  internalPort: 3001
  host: 0.0.0.0

# Health check for WebSocket server
healthCheck:
  path: /
  method: GET
  timeout: 10000
  gracePeriod: 30