#define ACCOUNT_EDITING      0
#define COMMENT_TO_SYSOP     1
#define DOWNLOAD             2
#define ENTER_MESSAGE        3
#define FILE_LISTINGS        4
#define JOIN_CONFERENCE      5
#define NEW_FILES_SINCE      6
#define PAGE_SYSOP           7
#define READ_MSG             8
#define DISPLAY_USER_STATS   9
#define UPLOAD               10
#define VIEW_A_FILE          11
#define EDIT_USER_INFO       12
#define REMOTE_SHELL         13
#define ZIPPY_TEXT_SEARCH    14
#define OVERRIDE_CHAT        15
#define EDIT_USER_NAME       16
#define EDIT_USER_LOCATION   17
#define EDIT_PHONE_NUMBER    18
#define EDIT_PASSWORD        19
#define SENTBY_FILES         20
#define DEFAULT_CHAT_ON      21
#define CLEAR_SCREEN_MSG     22
#define CAPITOLS_in_FILE     23
#define CHAT_COLOR_SYSOP     24
#define CHAT_COLOR_USER      25
#define VARYING_LINK_RATE    26
#define KEEP_UPLOAD_CREDIT   27
#define ALLOW_FREE_RESUMING  28
#define DO_CALLERSLOG        29
#define DO_UD_LOG            30
#define OVERRIDE_TIMES       41
#define BULLETINS            42
#define SYSOP_READ           43
#define NODE_NUMBER          44
#define SCREEN_TO_FRONT      45
#define ZOO                  46
#define PKAX                 47
#define LHARC                48
#define WARP                 49
#define ZIP                  50
