#define SV_UNICONIFY      153
#define SV_SYSOPLOG       154
#define SV_LOCALLOG       155
#define SV_ACCOUNTS       156
#define SV_CHAT           157
#define SV_NODEOFFHOOK    158
#define SV_EXITNODE       159
#define SV_INITMODEM      160
#define SV_WHATSUP        161
#define SV_INSTANT        170
#define SV_RESERVE        171
#define SV_CHATTOGGLE     172
#define SV_TOPS           173
#define SV_AESHELL        174
#define SV_START          176
#define SV_NEWMSG         177
#define SV_QUIETNODE      178
#define SV_SETNRAMS       179
#define SV_RESERVENAME    180

