[0m[2J[1m[11C____________   _____[6C__[6C____  ____________
[10C/[36m¢[34m[11C\[37m /[36m    ¢[34m)[37m    /[0m__[1;34m\[37m    /[36m¢[34m   \[37m/[36m[11C¢[34m\[0m
[10C\___/[1;34m    \[0m___[1;34m/[37m/[0m   __[1;34m/[0m__[1m  /[34m    \[37m  /[0m\_  __[1;34m\[0m___[1m/[34m    \[0m___[1;34m/[0m
[13C/[1;34m[6C\[37m  /[34m[9C\[37m/[36m¢[34m[5C\[37m/[0m   '[1;34m    \[37m /[34m[6C\[0m
[13C\[34m______[1m/[0m  \[34m_________[1m/[0m\[34m______[1m/[0m\[34m________[1m/[0m \[34m______[1m/[0miN7[36m
[14C~~~~~~    ~~~~~~~~~  ~~~~~~  ~~~~~~~~   ~~~~~~
[13C[1;31;41m>>[37m  TLiST /X version V2.0 by PHiDEAUX!/SRH [31m<<[32;40m

   [32m 1[33m} [35m2000ad      [32m13[33m} [35mExstacy      [32m25[33m} [35mMystic       [32m37[33m} [35mTechnoBrains
   [32m 2[33m} [35m4wd         [32m14[33m} [35mFaith        [32m26[33m} [35mNova Acies!  [32m38[33m} [35mTRSI
   [32m 3[33m} [35mAddonic     [32m15[33m} [35mFairlight    [32m27[33m} [35mNightfall    [32m39[33m} [35mThe Silents
   [32m 4[33m} [35mAFL         [32m16[33m} [35mG0D          [32m28[33m} [35mOutlaws      [32m40[33m} [35mUnited Forces
   [32m 5[33m} [35mAnthrox     [32m17[33m} [35mHardCore Dzn [32m29[33m} [35mParadox      [32m41[33m} [35mX Trade
   [32m 6[33m} [35mCrystal     [32m18[33m} [35mHoodlum      [32m30[33m} [35mQuartex      [32m42[33m} [35mZenith
   [32m 7[33m} [35mD & R       [32m19[33m} [35mHumane       [32m31[33m} [35mScoopex      [32m  [33m  [35m   
   [32m 8[33m} [35mDCS         [32m20[33m} [35mI.N.C.       [32m32[33m} [35mShades       [32m43[33m} [35mMisc. Groups
   [32m 9[33m} [35mDecade      [32m21[33m} [35mInteractive  [32m33[33m} [35mSRH          [32m44[33m} [35mINDEPENDENTS
   [32m10[33m} [35mDelirium    [32m22[33m} [35mJustice      [32m34[33m} [35mSupplex      [32m45[33m} [35mAll Groups  
   [32m11[33m} [35mDigital     [32m23[33m} [35mLSD          [32m35[33m} [35mSyndicate    [32m  [33m  [35m          
   [32m12[33m} [35mDesire      [32m24[33m} [35mMotion       [32m36[33m} [35mTarkus Team  [32m46[33m} [35mCountry Menu

