/**
 * C64 40-col plan, Task 7 - REACHABILITY.
 *
 * tests/utils/ansi-art-detect.util.test.ts pins the decision function.
 * This file proves the decision is WIRED: it drives the product's real
 * entry point, `displayScreen(socket, session, screenName)`, through the
 * real (unmocked) `loadScreenFile`, and asserts what actually goes on the
 * wire for
 *   - a PETSCII session on a prose .TXT   -> reflowed to 40 columns,
 *   - a PETSCII session on an ANSI-art screen -> the skip token, no art,
 *   - an ANSI session on the same files   -> byte-identical to before.
 *
 * The absolute-path seam (screenName forwarded verbatim into
 * loadScreenFile's isAbsolutePath branch) and the emit-spy socket mock
 * follow tests/handlers/petscii-bytes-transport.test.ts.
 */
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';

process.env.SKIP_DB_INIT = '1';

import { displayScreen } from '../../src/handlers/screen.handler';
import { ANSI_ART_SKIPPED_NOTICE } from '../../src/utils/ansi-art-detect.util';
import { printableLength } from '../../src/utils/wrap-for-session.util';

/** A paragraph whose every line is far wider than a C64's 40 columns. */
const PROSE_LINES = [
  'Welcome to the board! This opening line is deliberately much wider than forty columns.',
  'Today we have new files in the Amiga conference, uploaded by the usual suspects.',
  'Read the rules before you upload anything, and please do not flood the message base.',
  'Enjoy your stay.',
];
const PROSE = PROSE_LINES.join('\r\n') + '\r\n';

/** CP437 block elements: an 80-column picture, built as BYTES. */
const ART_BYTES = Buffer.concat(
  Array.from({ length: 10 }, () =>
    Buffer.concat([
      Buffer.from(Array.from({ length: 78 }, (_, i) => [0xdb, 0xdc, 0xdf, 0xb0, 0xb1, 0xb2][i % 6])),
      Buffer.from('\r\n', 'latin1'),
    ])
  )
);

/**
 * What the art file looks like ON THE WIRE: `loadScreenFile` maps CP437
 * high bytes to their Unicode equivalents before `displayScreen` ever sees
 * them, so 0xDB/0xDC/0xDF arrive as the full/lower/upper block glyphs.
 */
const UNICODE_BLOCKS = String.fromCharCode(0x2588, 0x2584, 0x2580);
/** The six glyphs of one source row, in order, as they reach the wire. */
const UNICODE_BLOCK_RUN = String.fromCharCode(0x2588, 0x2584, 0x2580, 0x2591, 0x2592, 0x2593);

const REPO_ROOT = path.resolve(__dirname, '../../../..');

let tmpDir: string;
let prosePath: string;
let artPath: string;
let menuPath: string;

beforeAll(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'petscii-reflow-'));
  prosePath = path.join(tmpDir, 'PROSE.TXT');
  artPath = path.join(tmpDir, 'ARTSCRN.TXT');
  menuPath = path.join(tmpDir, 'MENU.TXT');
  fs.writeFileSync(prosePath, Buffer.from(PROSE, 'latin1'));
  fs.writeFileSync(artPath, ART_BYTES);

  // The REAL board menu (MENU250.TXT: 17 art rows of 23, share 0.74 - art
  // by every measure) with only its leading `~WX` wipe directive dropped.
  // The wipe is out of scope here: its frames are generated by
  // getWipeFrames and never pass through wrapForSession, so an 80-column
  // noise frame would drown the assertion this test is making. Everything
  // that matters - the ASCII masthead and the command list - is unchanged.
  const realMenu = fs.readFileSync(path.join(REPO_ROOT, 'Screens/MENU250.TXT'), 'latin1');
  fs.writeFileSync(menuPath, Buffer.from(realMenu.split(/\r?\n/).slice(1).join('\r\n'), 'latin1'));
});

let seq = 0;
async function show(screenPath: string, session: any): Promise<string> {
  const emitted: Array<{ event: string; data: any }> = [];
  const socket = {
    // getAnsiBuffer (reached via displayScreen's flushOutput) keys its
    // buffer map on socket.id and registers a 'disconnect' listener.
    id: `petscii-reflow-${seq++}`,
    emit: (event: string, data: any) => emitted.push({ event, data }),
    on: () => {},
  };
  const ok = await displayScreen(socket as any, session, screenPath);
  expect(ok).toBe(true);
  return emitted
    .filter((e) => e.event === 'ansi-output')
    .map((e) => String(e.data))
    .join('');
}

/** Content rows of an emitted frame, with the frame's cursor-hide/show wrapper dropped. */
function contentRows(out: string): string[] {
  return out
    .replace(/\x1b\[\?25[lh]/g, '')
    .replace(/^\x1b\[[0-9;]*[HJ]/, '')
    .split('\r\n')
    .filter((l) => l.replace(/\x1b\[[0-9;]*[A-Za-z]/g, '').trim().length > 0);
}

describe('PETSCII text-screen fallback on the real displayScreen path', () => {
  it('reflows a prose .TXT to 40 columns for a petsciiMode session', async () => {
    const out = await show(prosePath, { petsciiMode: true, screenWidth: 40, nodeId: 0 });

    const rows = contentRows(out);
    // Every row now fits a C64 screen...
    for (const row of rows) {
      expect(printableLength(row)).toBeLessThanOrEqual(40);
    }
    // ...and the wide source lines were really split, not truncated: more
    // rows out than in, and every word survives.
    expect(rows.length).toBeGreaterThan(PROSE_LINES.length);
    expect(out).not.toContain(PROSE_LINES[0]);
    for (const word of PROSE_LINES[0].split(' ')) {
      expect(out).toContain(word);
    }
  });

  it('skips an ANSI-art screen with the ASCII token instead of smearing it', async () => {
    const out = await show(artPath, { petsciiMode: true, screenWidth: 40, nodeId: 0 });

    expect(out).toBe(ANSI_ART_SKIPPED_NOTICE);
    expect(out).not.toContain(UNICODE_BLOCKS);
  });

  it('leaves an ANSI (non-petscii) session byte-identical on the SAME prose file', async () => {
    const out = await show(prosePath, { nodeId: 0, screenWidth: 80 });

    for (const line of PROSE_LINES) {
      expect(out).toContain(line); // unwrapped, verbatim
    }
    expect(contentRows(out)).toHaveLength(PROSE_LINES.length);
  });

  it('leaves an ANSI (non-petscii) session byte-identical on the SAME art file', async () => {
    const out = await show(artPath, { nodeId: 0, screenWidth: 80 });

    expect(out).not.toContain(ANSI_ART_SKIPPED_NOTICE);

    // Not just "some blocks survived" - a wrongly-wrapped ANSI session would
    // pass that. Every content row is still the full 78-column source row.
    const rows = contentRows(out);
    expect(rows).toHaveLength(10);
    for (const row of rows) {
      expect(printableLength(row)).toBe(78);
    }
    expect(rows[0]).toBe(
      Array.from({ length: 78 }, (_, i) => UNICODE_BLOCK_RUN[i % 6]).join('')
    );
  });

  /**
   * CRITICAL (review of 4d9020d9a): MENU scores as art (MENU.TXT 0.45,
   * MENU250.TXT 0.74) and MENU is in SCREENS_REQUIRE_CLEAR, so an art-skip
   * left a C64 caller with a cleared screen, the skip token, and no command
   * list at all - and there is no MENU*.seq to fall back to. A folded menu
   * is navigable; a skipped one is not.
   */
  it('never art-skips a menu for a petsciiMode session - the command list survives, folded to 40', async () => {
    const out = await show(menuPath, { petsciiMode: true, screenWidth: 40, nodeId: 0 });

    expect(out).not.toContain(ANSI_ART_SKIPPED_NOTICE);

    // The command list is still there. Compared on the ANSI-stripped text
    // with row breaks removed, so a wrap landing mid-label cannot hide it.
    // Folding 23 source rows to 40 columns doubles them past a screenful, so
    // this is page ONE and it ends in the normal More? prompt - which is the
    // point: the menu is paginated and navigable, not replaced by a token.
    const flat = out.replace(/\x1b\[[0-9;?]*[A-Za-z]/g, '').replace(/[\r\n]/g, ' ').replace(/\s+/g, ' ');
    for (const label of ['UPLOAD FILE(S)', 'DOWNLOAD FILE(S)', 'ZIPPY SEARCH']) {
      expect(flat).toContain(label);
    }
    expect(flat).toContain('More(y/n/ns)?');

    // ...and it fits a C64 screen.
    for (const row of contentRows(out)) {
      expect(printableLength(row)).toBeLessThanOrEqual(40);
    }
  });

  /**
   * INVERTED 2026-09-02 (whole-run review, I1). This case used to assert that
   * a petsciiMode session carrying screenWidth 80 got NO reflow, on the
   * reading that such a caller is "a C64 emulator in 80-col mode". That is
   * not what the number means anywhere else on the board: doorScreenWidth()
   * - the one width authority, which BB_SCRWIDTH, the launch-time lineWrap
   * and BBSApi.getTerminalSize() all read - treats a PETSCII session's 80 as
   * the STALE 80 a web caller's xterm reported before the caller answered
   * `P`, and answers 40. index.ts's terminal-type listener makes that the
   * common case, not the exotic one: it sets petsciiMode and then calls
   * applyClientReportedGeometry(), which refuses to write geometry for a
   * PETSCII session, so nothing on that path ever stamps 40.
   *
   * The old assertion pinned the disagreement in place: prose ran off the
   * right edge of a screen every other reader knew was forty columns wide.
   */
  it('reflows a petsciiMode session carrying a stale 80 - one width authority', async () => {
    const out = await show(prosePath, { petsciiMode: true, screenWidth: 80, nodeId: 0 });

    // The over-wide source lines are gone: they arrived folded. (The last
    // PROSE_LINE is sixteen columns and survives a 40-column fold intact.)
    for (const line of PROSE_LINES.filter((l) => l.length > 40)) {
      expect(out).not.toContain(line);
    }
    for (const row of contentRows(out)) {
      expect(printableLength(row)).toBeLessThanOrEqual(40);
    }
    // ...and the words survived the fold.
    const flat = out.replace(/\x1b\[[0-9;?]*[A-Za-z]/g, '').replace(/[\r\n]/g, ' ').replace(/\s+/g, ' ');
    expect(flat).toContain('Welcome to the board!');
    expect(flat).toContain('Enjoy your stay.');
  });

  it('an ANSI session at 80 is still byte-identical on the same prose', async () => {
    const out = await show(prosePath, { screenWidth: 80, nodeId: 0 });
    for (const line of PROSE_LINES) {
      expect(out).toContain(line);
    }
  });
});
