/* Copyright (c) 1993 SAS Institute, Inc, Cary, NC USA */
/* All Rights Reserved. */

#ifndef _CONSTRUCTOR_H
#define _CONSTRUCTOR_H

#define CONSTRUCTOR(x) int __stdargs _STI_##x(void)
#define CONSTRUCTOR_P(x,n) CONSTRUCTOR(n##_##x)
#define CONSTRUCTOR_NAME(x,n) _STI_##n##_##x

#define DESTRUCTOR(x) void __stdargs _STD_##x(void)
#define DESTRUCTOR_P(x,n) DESTRUCTOR(n##_##x)
#define DESTRUCTOR_NAME(x,n) _STD_##n##_##x

#define FP_CONSTRUCTOR(x) CONSTRUCTOR_P(x,100)
#define FP_DESTRUCTOR(x) DESTRUCTOR_P(x,100)

#define CBMLIB_CONSTRUCTOR(x) CONSTRUCTOR_P(x,110)
#define CBMLIB_DESTRUCTOR(x) DESTRUCTOR_P(x,110)

#define CLOCK_CONSTRUCTOR(x) CONSTRUCTOR_P(x,150)
#define CLOCK_DESTRUCTOR(x) DESTRUCTOR_P(x,150)

#define PROFILE_CONSTRUCTOR(x) CONSTRUCTOR_P(x,150)
#define PROFILE_DESTRUCTOR(x) DESTRUCTOR_P(x,150)
#define PROFILE_DESTRUCTOR_NAME(x) DESTRUCTOR_NAME(x,150)

#define COVER_CONSTRUCTOR(x) CONSTRUCTOR_P(x,210)
#define COVER_DESTRUCTOR(x) DESTRUCTOR_P(x,210)

#define MEMCLEANUP_CONSTRUCTOR(x) CONSTRUCTOR_P(x,250)
#define MEMCLEANUP_DESTRUCTOR(x) DESTRUCTOR_P(x,250)

#define STACKEXT_CONSTRUCTOR(x) CONSTRUCTOR_P(x,250)
#define STACKEXT_DESTRUCTOR(x) DESTRUCTOR_P(x,250)

#define DFIND_CONSTRUCTOR(x) DESTRUCTOR_P(x,300)
#define DFIND_DESTRUCTOR(x) DESTRUCTOR_P(x,300)

#define STDIO_CONSTRUCTOR(x) CONSTRUCTOR_P(x,500)
#define STDIO_DESTRUCTOR(x) DESTRUCTOR_P(x,500)

#define CPPIO_CONSTRUCTOR(x) CONSTRUCTOR_P(x,4990)
#define CPPIO_DESTRUCTOR(x) DESTRUCTOR_P(x,4990)

#define CPP_CONSTRUCTOR(x) CONSTRUCTOR_P(x,5000)
#define CPP_DESTRUCTOR(x) DESTRUCTOR_P(x,5000)

#define DEFAULT_CONSTRUCTOR(x) CONSTRUCTOR_P(x,30000)
#define DEFAULT_DESTRUCTOR(x) DESTRUCTOR_P(x,30000)

#endif
