#include <exec/types.h>
#include <exec/ports.h>
#include <exec/memory.h>
#include <exec/execbase.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdarg.h>
#include <string.h>
#include <dos.h>
#include <stdlib.h>
#include "mempriv.h"
