// AUTO-GENERATED by dev/scripts/generate-lvo-maps.js
// Source: mcp-server/data/ndk-structs-index.json (NDK 3.1)
// Do not edit manually -- regenerate with: node dev/scripts/generate-lvo-maps.js

/**
 * Struct field layouts for key AmigaOS data structures.
 * Used for annotating memory accesses in 68K debug logging.
 * Only includes structs actively used in the emulator.
 */

export interface StructField {
  name: string;
  offset: number;
  size: number;
  type: string;
}

export const PROCESS_FIELDS: StructField[] = [
  { name: 'pr_Task', offset: 0, size: 92, type: 'STRUCT' },
  { name: 'pr_MsgPort', offset: 92, size: 34, type: 'STRUCT' },
  { name: 'pr_Pad', offset: 126, size: 2, type: 'WORD' },
  { name: 'pr_SegList', offset: 128, size: 4, type: 'BPTR' },
  { name: 'pr_StackSize', offset: 132, size: 4, type: 'LONG' },
  { name: 'pr_GlobVec', offset: 136, size: 4, type: 'APTR' },
  { name: 'pr_TaskNum', offset: 140, size: 4, type: 'LONG' },
  { name: 'pr_StackBase', offset: 144, size: 4, type: 'BPTR' },
  { name: 'pr_Result2', offset: 148, size: 4, type: 'LONG' },
  { name: 'pr_CurrentDir', offset: 152, size: 4, type: 'BPTR' },
  { name: 'pr_CIS', offset: 156, size: 4, type: 'BPTR' },
  { name: 'pr_COS', offset: 160, size: 4, type: 'BPTR' },
  { name: 'pr_ConsoleTask', offset: 164, size: 4, type: 'APTR' },
  { name: 'pr_FileSystemTask', offset: 168, size: 4, type: 'APTR' },
  { name: 'pr_CLI', offset: 172, size: 4, type: 'BPTR' },
  { name: 'pr_ReturnAddr', offset: 176, size: 4, type: 'APTR' },
  { name: 'pr_PktWait', offset: 180, size: 4, type: 'APTR' },
  { name: 'pr_WindowPtr', offset: 184, size: 4, type: 'APTR' },
  { name: 'pr_HomeDir', offset: 188, size: 4, type: 'BPTR' },
  { name: 'pr_Flags', offset: 192, size: 4, type: 'LONG' },
  { name: 'pr_ExitCode', offset: 196, size: 4, type: 'APTR' },
  { name: 'pr_ExitData', offset: 200, size: 4, type: 'LONG' },
  { name: 'pr_Arguments', offset: 204, size: 4, type: 'APTR' },
  { name: 'pr_LocalVars', offset: 208, size: 12, type: 'STRUCT' },
  { name: 'pr_ShellPrivate', offset: 220, size: 4, type: 'APTR' },
  { name: 'pr_CES', offset: 224, size: 4, type: 'BPTR' },
];

export const COMMANDLINEINTERFACE_FIELDS: StructField[] = [
  { name: 'cli_Result2', offset: 0, size: 4, type: 'LONG' },
  { name: 'cli_SetName', offset: 4, size: 4, type: 'BSTR' },
  { name: 'cli_CommandDir', offset: 8, size: 4, type: 'BPTR' },
  { name: 'cli_ReturnCode', offset: 12, size: 4, type: 'LONG' },
  { name: 'cli_CommandName', offset: 16, size: 4, type: 'BSTR' },
  { name: 'cli_FailLevel', offset: 20, size: 4, type: 'LONG' },
  { name: 'cli_Prompt', offset: 24, size: 4, type: 'BSTR' },
  { name: 'cli_StandardInput', offset: 28, size: 4, type: 'BPTR' },
  { name: 'cli_CurrentInput', offset: 32, size: 4, type: 'BPTR' },
  { name: 'cli_CommandFile', offset: 36, size: 4, type: 'BSTR' },
  { name: 'cli_Interactive', offset: 40, size: 4, type: 'LONG' },
  { name: 'cli_Background', offset: 44, size: 4, type: 'LONG' },
  { name: 'cli_CurrentOutput', offset: 48, size: 4, type: 'BPTR' },
  { name: 'cli_DefaultStack', offset: 52, size: 4, type: 'LONG' },
  { name: 'cli_StandardOutput', offset: 56, size: 4, type: 'BPTR' },
  { name: 'cli_Module', offset: 60, size: 4, type: 'BPTR' },
];

export const FILEHANDLE_FIELDS: StructField[] = [
  { name: 'fh_Link', offset: 0, size: 4, type: 'APTR' },
  { name: 'fh_Interactive', offset: 4, size: 4, type: 'APTR' },
  { name: 'fh_Type', offset: 8, size: 4, type: 'APTR' },
  { name: 'fh_Buf', offset: 12, size: 4, type: 'LONG' },
  { name: 'fh_Pos', offset: 16, size: 4, type: 'LONG' },
  { name: 'fh_End', offset: 20, size: 4, type: 'LONG' },
  { name: 'fh_Funcs', offset: 24, size: 4, type: 'LONG' },
];

export const FILELOCK_FIELDS: StructField[] = [
  { name: 'fl_Link', offset: 0, size: 4, type: 'BPTR' },
  { name: 'fl_Key', offset: 4, size: 4, type: 'LONG' },
  { name: 'fl_Access', offset: 8, size: 4, type: 'LONG' },
  { name: 'fl_Task', offset: 12, size: 4, type: 'APTR' },
  { name: 'fl_Volume', offset: 16, size: 4, type: 'BPTR' },
];

export const IOEXTTD_FIELDS: StructField[] = [
  { name: 'IOTD_COUNT', offset: 48, size: 4, type: 'ULONG' },
  { name: 'IOTD_SECLABEL', offset: 52, size: 4, type: 'ULONG' },
];

export const EXECBASE_FIELDS: StructField[] = [
  { name: 'SoftVer', offset: 34, size: 2, type: 'UWORD' },
  { name: 'LowMemChkSum', offset: 36, size: 2, type: 'WORD' },
  { name: 'ChkBase', offset: 38, size: 4, type: 'ULONG' },
  { name: 'ColdCapture', offset: 42, size: 4, type: 'APTR' },
  { name: 'CoolCapture', offset: 46, size: 4, type: 'APTR' },
  { name: 'WarmCapture', offset: 50, size: 4, type: 'APTR' },
  { name: 'SysStkUpper', offset: 54, size: 4, type: 'APTR' },
  { name: 'SysStkLower', offset: 58, size: 4, type: 'APTR' },
  { name: 'MaxLocMem', offset: 62, size: 4, type: 'ULONG' },
  { name: 'DebugEntry', offset: 66, size: 4, type: 'APTR' },
  { name: 'DebugData', offset: 70, size: 4, type: 'APTR' },
  { name: 'AlertData', offset: 74, size: 4, type: 'APTR' },
  { name: 'MaxExtMem', offset: 78, size: 4, type: 'APTR' },
  { name: 'ChkSum', offset: 82, size: 2, type: 'WORD' },
  { name: 'IVTBE', offset: 84, size: 12, type: 'STRUCT' },
  { name: 'IVDSKBLK', offset: 96, size: 12, type: 'STRUCT' },
  { name: 'IVSOFTINT', offset: 108, size: 12, type: 'STRUCT' },
  { name: 'IVPORTS', offset: 120, size: 12, type: 'STRUCT' },
  { name: 'IVCOPER', offset: 132, size: 12, type: 'STRUCT' },
  { name: 'IVVERTB', offset: 144, size: 12, type: 'STRUCT' },
  { name: 'IVBLIT', offset: 156, size: 12, type: 'STRUCT' },
  { name: 'IVAUD0', offset: 168, size: 12, type: 'STRUCT' },
  { name: 'IVAUD1', offset: 180, size: 12, type: 'STRUCT' },
  { name: 'IVAUD2', offset: 192, size: 12, type: 'STRUCT' },
  { name: 'IVAUD3', offset: 204, size: 12, type: 'STRUCT' },
  { name: 'IVRBF', offset: 216, size: 12, type: 'STRUCT' },
  { name: 'IVDSKSYNC', offset: 228, size: 12, type: 'STRUCT' },
  { name: 'IVEXTER', offset: 240, size: 12, type: 'STRUCT' },
  { name: 'IVINTEN', offset: 252, size: 12, type: 'STRUCT' },
  { name: 'IVNMI', offset: 264, size: 12, type: 'STRUCT' },
  { name: 'ThisTask', offset: 276, size: 4, type: 'APTR' },
  { name: 'IdleCount', offset: 280, size: 4, type: 'ULONG' },
  { name: 'DispCount', offset: 284, size: 4, type: 'ULONG' },
  { name: 'Quantum', offset: 288, size: 2, type: 'UWORD' },
  { name: 'Elapsed', offset: 290, size: 2, type: 'UWORD' },
  { name: 'SysFlags', offset: 292, size: 2, type: 'UWORD' },
  { name: 'IDNestCnt', offset: 294, size: 1, type: 'BYTE' },
  { name: 'TDNestCnt', offset: 295, size: 1, type: 'BYTE' },
  { name: 'AttnFlags', offset: 296, size: 2, type: 'UWORD' },
  { name: 'AttnResched', offset: 298, size: 2, type: 'UWORD' },
  { name: 'ResModules', offset: 300, size: 4, type: 'APTR' },
  { name: 'TaskTrapCode', offset: 304, size: 4, type: 'APTR' },
  { name: 'TaskExceptCode', offset: 308, size: 4, type: 'APTR' },
  { name: 'TaskExitCode', offset: 312, size: 4, type: 'APTR' },
  { name: 'TaskSigAlloc', offset: 316, size: 4, type: 'ULONG' },
  { name: 'TaskTrapAlloc', offset: 320, size: 2, type: 'UWORD' },
  { name: 'MemList', offset: 322, size: 14, type: 'STRUCT' },
  { name: 'ResourceList', offset: 336, size: 14, type: 'STRUCT' },
  { name: 'DeviceList', offset: 350, size: 14, type: 'STRUCT' },
  { name: 'IntrList', offset: 364, size: 14, type: 'STRUCT' },
  { name: 'LibList', offset: 378, size: 14, type: 'STRUCT' },
  { name: 'PortList', offset: 392, size: 14, type: 'STRUCT' },
  { name: 'TaskReady', offset: 406, size: 14, type: 'STRUCT' },
  { name: 'TaskWait', offset: 420, size: 14, type: 'STRUCT' },
  { name: 'SoftInts', offset: 434, size: 16, type: 'STRUCT' },
  { name: 'LastAlert', offset: 450, size: 4, type: 'STRUCT' },
  { name: 'VBlankFrequency', offset: 454, size: 1, type: 'UBYTE' },
  { name: 'PowerSupplyFrequency', offset: 455, size: 1, type: 'UBYTE' },
  { name: 'SemaphoreList', offset: 456, size: 14, type: 'STRUCT' },
  { name: 'KickMemPtr', offset: 470, size: 4, type: 'APTR' },
  { name: 'KickTagPtr', offset: 474, size: 4, type: 'APTR' },
  { name: 'KickCheckSum', offset: 478, size: 4, type: 'APTR' },
  { name: 'ex_Pad0', offset: 482, size: 2, type: 'UWORD' },
  { name: 'ex_LaunchPoint', offset: 484, size: 4, type: 'ULONG' },
  { name: 'ex_RamLibPrivate', offset: 488, size: 4, type: 'APTR' },
  { name: 'ex_EClockFrequency', offset: 492, size: 4, type: 'ULONG' },
  { name: 'ex_CacheControl', offset: 496, size: 4, type: 'ULONG' },
  { name: 'ex_TaskID', offset: 500, size: 4, type: 'ULONG' },
  { name: 'ex_Reserved1', offset: 504, size: 5, type: 'STRUCT' },
  { name: 'ex_MMULock', offset: 509, size: 4, type: 'APTR' },
  { name: 'ex_Reserved2', offset: 513, size: 3, type: 'STRUCT' },
  { name: 'ex_MemHandlers', offset: 516, size: 12, type: 'STRUCT' },
  { name: 'ex_MemHandler', offset: 528, size: 4, type: 'APTR' },
];

export const DOSPACKET_FIELDS: StructField[] = [
  { name: 'dp_Link', offset: 0, size: 4, type: 'APTR' },
  { name: 'dp_Port', offset: 4, size: 4, type: 'APTR' },
  { name: 'dp_Type', offset: 8, size: 4, type: 'LONG' },
  { name: 'dp_Res1', offset: 12, size: 4, type: 'LONG' },
  { name: 'dp_Res2', offset: 16, size: 4, type: 'LONG' },
  { name: 'dp_Arg1', offset: 20, size: 4, type: 'LONG' },
];

export const FILEINFOBLOCK_FIELDS: StructField[] = [
  { name: 'fib_DiskKey', offset: 0, size: 4, type: 'LONG' },
  { name: 'fib_DirEntryType', offset: 4, size: 4, type: 'LONG' },
  { name: 'fib_FileName', offset: 8, size: 108, type: 'STRUCT' },
  { name: 'fib_Protection', offset: 116, size: 4, type: 'LONG' },
  { name: 'fib_EntryType', offset: 120, size: 4, type: 'LONG' },
  { name: 'fib_Size', offset: 124, size: 4, type: 'LONG' },
  { name: 'fib_NumBlocks', offset: 128, size: 4, type: 'LONG' },
  { name: 'fib_DateStamp', offset: 132, size: 12, type: 'STRUCT' },
  { name: 'fib_Comment', offset: 144, size: 80, type: 'STRUCT' },
  { name: 'fib_OwnerUID', offset: 224, size: 2, type: 'UWORD' },
  { name: 'fib_OwnerGID', offset: 226, size: 2, type: 'UWORD' },
  { name: 'fib_Reserved', offset: 228, size: 32, type: 'STRUCT' },
];

export const DATESTAMP_FIELDS: StructField[] = [
  { name: 'ds_Days', offset: 0, size: 4, type: 'LONG' },
  { name: 'ds_Minute', offset: 4, size: 4, type: 'LONG' },
  { name: 'ds_Tick', offset: 8, size: 4, type: 'LONG' },
];

export const ROOTNODE_FIELDS: StructField[] = [
  { name: 'rn_TaskArray', offset: 0, size: 4, type: 'BPTR' },
  { name: 'rn_ConsoleSegment', offset: 4, size: 4, type: 'BPTR' },
  { name: 'rn_Time', offset: 8, size: 12, type: 'STRUCT' },
  { name: 'rn_RestartSeg', offset: 20, size: 4, type: 'LONG' },
  { name: 'rn_Info', offset: 24, size: 4, type: 'BPTR' },
  { name: 'rn_FileHandlerSegment', offset: 28, size: 4, type: 'BPTR' },
  { name: 'rn_CliList', offset: 32, size: 12, type: 'STRUCT' },
  { name: 'rn_BootProc', offset: 44, size: 4, type: 'APTR' },
  { name: 'rn_ShellSegment', offset: 48, size: 4, type: 'BPTR' },
  { name: 'rn_Flags', offset: 52, size: 4, type: 'LONG' },
];

export const DOSINFO_FIELDS: StructField[] = [
  { name: 'di_McName', offset: 0, size: 4, type: 'BPTR' },
];

export const DEVICENODE_FIELDS: StructField[] = [
  { name: 'dn_Next', offset: 0, size: 4, type: 'BPTR' },
  { name: 'dn_Type', offset: 4, size: 4, type: 'ULONG' },
  { name: 'dn_Task', offset: 8, size: 4, type: 'CPTR' },
  { name: 'dn_Lock', offset: 12, size: 4, type: 'BPTR' },
  { name: 'dn_Handler', offset: 16, size: 4, type: 'BSTR' },
  { name: 'dn_StackSize', offset: 20, size: 4, type: 'ULONG' },
  { name: 'dn_Priority', offset: 24, size: 4, type: 'LONG' },
  { name: 'dn_Startup', offset: 28, size: 4, type: 'BPTR' },
  { name: 'dn_SegList', offset: 32, size: 4, type: 'BPTR' },
  { name: 'dn_GlobalVec', offset: 36, size: 4, type: 'BPTR' },
  { name: 'dn_Name', offset: 40, size: 4, type: 'BSTR' },
];

export const DEVPROC_FIELDS: StructField[] = [
  { name: 'dvp_Port', offset: 0, size: 4, type: 'APTR' },
  { name: 'dvp_Lock', offset: 4, size: 4, type: 'BPTR' },
  { name: 'dvp_Flags', offset: 8, size: 4, type: 'ULONG' },
  { name: 'dvp_DevNode', offset: 12, size: 4, type: 'APTR' },
];

export const SEGMENT_FIELDS: StructField[] = [
  { name: 'seg_Next', offset: 0, size: 4, type: 'BPTR' },
  { name: 'seg_UC', offset: 4, size: 4, type: 'LONG' },
  { name: 'seg_Seg', offset: 8, size: 4, type: 'BPTR' },
  { name: 'seg_Name', offset: 12, size: 4, type: 'STRUCT' },
];

/** Struct name (case-insensitive) -> field layout */
export const STRUCT_FIELDS: Record<string, StructField[]> = {
  'process': PROCESS_FIELDS,
  'commandlineinterface': COMMANDLINEINTERFACE_FIELDS,
  'filehandle': FILEHANDLE_FIELDS,
  'filelock': FILELOCK_FIELDS,
  'ioexttd': IOEXTTD_FIELDS,
  'execbase': EXECBASE_FIELDS,
  'dospacket': DOSPACKET_FIELDS,
  'fileinfoblock': FILEINFOBLOCK_FIELDS,
  'datestamp': DATESTAMP_FIELDS,
  'rootnode': ROOTNODE_FIELDS,
  'dosinfo': DOSINFO_FIELDS,
  'devicenode': DEVICENODE_FIELDS,
  'devproc': DEVPROC_FIELDS,
  'segment': SEGMENT_FIELDS,
};

/**
 * Look up what field is at a given offset within a struct.
 * Returns the field that contains the offset, or undefined.
 */
export function getFieldAtOffset(structName: string, offset: number): StructField | undefined {
  const fields = STRUCT_FIELDS[structName.toLowerCase()];
  if (!fields) return undefined;
  // Find the field whose range [offset, offset+size) contains the target
  for (const f of fields) {
    if (offset >= f.offset && offset < f.offset + f.size) return f;
  }
  return undefined;
}
