// ESM wrapper for CJS blessed exports
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const blessed = require('../../../../dist/engines/ui/blessed/index.js');

// Re-export all named exports
export const Screen = blessed.Screen;
export const Element = blessed.Element;
export const Program = blessed.Program;
export const EventEmitter = blessed.EventEmitter;
export const KeyBindings = blessed.KeyBindings;
export const ResponsiveLayoutManager = blessed.ResponsiveLayoutManager;
export const colors = blessed.colors;
export const Box = blessed.Box;
export const Text = blessed.Text;
export const List = blessed.List;
export const Form = blessed.Form;
export const Textbox = blessed.Textbox;
export const Input = blessed.Input;
export const Textarea = blessed.Textarea;
export const Button = blessed.Button;
export const ProgressBar = blessed.ProgressBar;
export const Table = blessed.Table;
export const Log = blessed.Log;
export const ScrollableBox = blessed.ScrollableBox;
export const ScrollableText = blessed.ScrollableText;
export const Checkbox = blessed.Checkbox;
export const RadioButton = blessed.RadioButton;
export const RadioSet = blessed.RadioSet;
export const Message = blessed.Message;
export const Question = blessed.Question;
export const Prompt = blessed.Prompt;
export const Loading = blessed.Loading;
export const Line = blessed.Line;
export const Listbar = blessed.Listbar;
export const BigText = blessed.BigText;
export const FileManager = blessed.FileManager;
export const Overlay = blessed.Overlay;
export const ListTable = blessed.ListTable;
export const ANSIImage = blessed.ANSIImage;
export const Terminal = blessed.Terminal;
export const Layout = blessed.Layout;
export const PassBox = blessed.PassBox;
export const FileBox = blessed.FileBox;
export const Image = blessed.Image;
export const Viewport = blessed.Viewport;
export const Canvas = blessed.Canvas;
export const IFrame = blessed.IFrame;
export const Video = blessed.Video;
export const ContextMenu = blessed.ContextMenu;
export const Panel = blessed.Panel;
export const DockablePanel = blessed.DockablePanel;

// Factory functions
export const screen = blessed.screen;
export const box = blessed.box;
export const text = blessed.text;
export const list = blessed.list;
export const form = blessed.form;
export const textbox = blessed.textbox;
export const input = blessed.input;
export const textarea = blessed.textarea;
export const button = blessed.button;
export const progressbar = blessed.progressbar;
export const table = blessed.table;
export const log = blessed.log;
export const scrollablebox = blessed.scrollablebox;
export const scrollabletext = blessed.scrollabletext;
export const checkbox = blessed.checkbox;
export const radiobutton = blessed.radiobutton;
export const radioset = blessed.radioset;
export const message = blessed.message;
export const question = blessed.question;
export const prompt = blessed.prompt;
export const loading = blessed.loading;
export const line = blessed.line;
export const listbar = blessed.listbar;
export const bigtext = blessed.bigtext;
export const filemanager = blessed.filemanager;
export const overlay = blessed.overlay;
export const listtable = blessed.listtable;
export const ansiimage = blessed.ansiimage;
export const terminal = blessed.terminal;
export const layout = blessed.layout;
export const passbox = blessed.passbox;
export const filebox = blessed.filebox;
export const image = blessed.image;
export const viewport = blessed.viewport;
export const canvas = blessed.canvas;
export const iframe = blessed.iframe;
export const video = blessed.video;

// Modal helpers
export const modalHelpers = blessed.modalHelpers;
export const centerElement = blessed.centerElement;
export const makeModalResponsive = blessed.makeModalResponsive;
export const createModalBackdrop = blessed.createModalBackdrop;
export const showModal = blessed.showModal;

// Default export
export default blessed.default || blessed;
