
[0;4;31m                                                                              [0m
[47;4;31m NewUser Wall v1.2 by Json / CReeD                         (C)1993 Js-/XTools [0m
[30m------------------------------------------------------------------------------[0m

spot                                                                          
                                                                              
                                                                              
                                                                              
                                                                              
                                                                              
[30m------------------------------------------------------------------------------[0m
[0;4;31m                                                                              [0m
[47;4;31m Anybody knows these guys?? Then please leave a msg to the Sysop about them!! [0m
