
[32mTodays Uploads in [33m>> Amiga Elite ! <<[34m :      [0m([35mFiles[33m: [36m13[0m, [35mFakes[33m: [36m00, [35mMegs[33m: [36m07.0[0m)
[35mYesterdays Statistics [0m: [32m08 [36mFiles[33m, [32m02 [36mFakes[33m, [32m02.5 [36mMegs [33m![0m

     [0m-J-Z2TR.DMS   [0mEPIXDEEP.EXE  [0m-D-STD2P.DMS  [0mA&D.DMS       [0mIPL_SKA.DMS   
     [0mSCX-Z2TR.LHA  [0mPOPL40CR.LHA  [0mFLT-JP1.DMS   [0mFLT-JP2.DMS   [0mFLT-JP3.DMS   
     [0mFLT-JP4A.DMS  [0mFLT-JP4B.DMS  [0mFLT-JP5.DMS   

[32mTodays Uploads in [33m>> SNES Only ! <<[34m :        [0m([35mFiles[33m: [36m01[0m, [35mFakes[33m: [36m00, [35mMegs[33m: [36m01.6[0m)
[35mYesterdays Statistics [0m: [32m01 [36mFiles[33m, [32m00 [36mFakes[33m, [32m00.0 [36mMegs [33m![0m

     [0mPS-16FF2.LZH  

[32mTodays Uploads in [33m>> The Musicbox ! <<[34m :     [0m([35mFiles[33m: [36m00[0m, [35mFakes[33m: [36m00, [35mMegs[33m: [36m00.0[0m)
[35mYesterdays Statistics [0m: [32m00 [36mFiles[33m, [32m00 [36mFakes[33m, [32m00.0 [36mMegs [33m![0m

[44;33m  QuickNew V2.1 by Calypso/GOD    [36m     Date : 04-06-94    [35m    Time : 14:29:10  

