*CONFTOP  XM010Doors:Amiexpress/Conftop/Conftop.x
*FILECHK  XM010Doors:Dupecheck.x

----------------------------------------------------------------------------
Please NOTE:

When you want to launch another door after conftop on Amiexpress 2.xx, you
must make a file called (BBS:COMMANDS/BBSCMD/FILECHK.INFO). You can make it
0 bytes, doesn't mather. If Conftop founds that file, it will try to start a
door from BBS.CMD called (FILECHK).
----------------------------------------------------------------------------
